apiVersion: v1
kind: Pod
metadata:
  name: monpod1
  namespace: production
  labels:
   app: web
spec:
  containers:
  - name: moncontainer
    image: mmumshad/simple-webapp-color
    ports:
     - containerPort: 8080
    env:
     - name: APP_COLOR
       value: blue

